/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class readLocalFile_ReadFiile */

#ifndef _Included_readLocalFile_ReadFiile
#define _Included_readLocalFile_ReadFiile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     readLocalFile_ReadFiile
 * Method:    getOOM
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_readLocalFile_ReadFiile_getOOM
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
